Add static-libs installation
Cisco-Talos/clamav pull request #1100
Opened 2023-11-27 10:02 UTC by driverxdw

add static library installation in CMakeLists.txt of libclamav submodules

2023-11-27 15:37 UTC, micahsnyder commented
Manual testing on Linux looks good:
```
❯ ls -la install/lib/
total 42252
drwxr-xr-x 3 micah micah     4096 Nov 27 10:36 ./
drwxr-xr-x 8 micah micah     4096 Nov 27 10:36 ../
-rw-r--r-- 1 micah micah 38642020 Nov 27 10:36 libclamav_rust.a
-rw-r--r-- 1 micah micah  3696484 Nov 27 10:36 libclamav_static.a
-rw-r--r-- 1 micah micah   145808 Nov 27 10:35 libclammspack_static.a
-rw-r--r-- 1 micah micah    16110 Nov 27 10:35 libclamunrar_iface_static.a
-rw-r--r-- 1 micah micah   633086 Nov 27 10:35 libclamunrar_static.a
-rw-r--r-- 1 micah micah   108684 Nov 27 10:36 libfreshclam_static.a
drwxr-xr-x 2 micah micah     4096 Nov 27 10:36 pkgconfig/
```

2023-11-27 19:00 UTC, micahsnyder requested changes
I found that the windows static build fails without these suggested changes.

2023-11-27 19:00 UTC, micahsnyder commented on libclamunrar_iface/CMakeLists.txt
> +            install( FILES $<TARGET_PDB_FILE:clamunrar_iface> DESTINATION . OPTIONAL COMPONENT libraries )
```suggestion
```
This line is not required. The target name is wrong, but also PDB files do not exist for static libraries.

2023-11-28 06:14 UTC, driverxdw reviewed
I've fixed it, thank you for your suggestion!

2023-11-29 22:52 UTC, micahsnyder approved these changes
Looks good now, thanks!

2023-11-30 23:19 UTC, merged