Clam 2256 add alz support (NOT READY TO MERGE)
Cisco-Talos/clamav pull request #1183
Opened 2024-02-23 22:05 UTC by ragusaa

2024-03-15 13:52 UTC, micahsnyder commented
PR needs to be rebased with the upstream main branch to bump the FLEVEL to 210 so ALZ file type detection works and tests pass, and to resolve merge conflicts.

2024-03-15 14:00 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +    ) -> Result<(), Box<dyn std::error::Error>> {
This is pretty hardcore, using `Box<dyn ... >`. But there is an easier way to pass back different types of errors.

2024-03-15 14:07 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +    }
```suggestion
    pub fn parse(&mut self, cursor: &mut std::io::Cursor<&Vec<u8>>) -> Result<(), Error> {
        self.head.file_name_length = cursor
            .read_u16::<LittleEndian>()
            .map_err(|_| Error::Read("file_name_length"))?;
        self.head.file_attribute = cursor
            .read_u8()
            .map_err(|_| Error::Read("file_attribute"))?;
        self.head.file_time_date = cursor
            .read_u32::<LittleEndian>()
            .map_err(|_| Error::Read("file_time_date"))?;
        self.head.file_descriptor = cursor
            .read_u8()
            .map_err(|_| Error::Read("file_descriptor"))?;
        self.head.unknown = cursor.read_u8().map_err(|_| Error::Read("unknown u8"))?;

        if 0 == self.head.file_name_length {
            return Err(Error::Parse("File Name Length is zero"));
        }

        let byte_len = self.head.file_descriptor / 0x10;
        if byte_len > 0 {
            self.compression_method = cursor
                .read_u8()
                .map_err(|_| Error::Read("compression_method"))?;
            self.unknown = cursor.read_u8().map_err(|_| Error::Read("unknown u8"))?;
            self.file_crc = cursor
                .read_u32::<LittleEndian>()
                .map_err(|_| Error::Read("file_crc"))?;

            match byte_len {
                1 => {
                    self.compressed_size = u64::from(
                        cursor
                            .read_u8()
                            .map_err(|_| Error::Read("compressed_size"))?,
                    );
                    self.uncompressed_size = u64::from(
                        cursor
                            .read_u8()
                            .map_err(|_| Error::Read("uncompressed_size"))?,
                    );
                }
                2 => {
                    self.compressed_size = u64::from(
                        cursor
                            .read_u16::<LittleEndian>()
                            .map_err(|_| Error::Read("compressed_size"))?,
                    );
                    self.uncompressed_size = u64::from(
                        cursor
                            .read_u16::<LittleEndian>()
                            .map_err(|_| Error::Read("uncompressed_size"))?,
                    );
                }
                4 => {
                    self.compressed_size = u64::from(
                        cursor
                            .read_u32::<LittleEndian>()
                            .map_err(|_| Error::Read("compressed_size"))?,
                    );
                    self.uncompressed_size = u64::from(
                        cursor
                            .read_u32::<LittleEndian>()
                            .map_err(|_| Error::Read("uncompressed_size"))?,
                    );
                }
                8 => {
                    self.compressed_size = cursor
                        .read_u64::<LittleEndian>()
                        .map_err(|_| Error::Read("compressed_size"))?;
                    self.uncompressed_size = cursor
                        .read_u64::<LittleEndian>()
                        .map_err(|_| Error::Read("uncompressed_size"))?;
                }
                _ => return Err(Error::Parse("Unsupported File Descriptor")),
            }
        }

        #[allow(clippy::cast_possible_truncation)]
        let idx0: usize = cursor.position() as usize;
        let idx1: usize = idx0 + self.head.file_name_length as usize;

        if idx1 > cursor.get_ref().len() {
            return Err(Error::Parse("Invalid file name length"));
        }

        let filename = &cursor.get_ref().as_slice()[idx0..idx1];
        cursor.set_position(idx1 as u64);

        self.file_name = String::from_utf8_lossy(filename).into_owned();

        if self.is_encrypted() {
            cursor
                .read_exact(&mut self.enc_chk)
                .map_err(|_| Error::Read("encrypted buffer"))?;
        }

        self.start_of_compressed_data = cursor.position();
        cursor.set_position(self.start_of_compressed_data + self.compressed_size);

        if self.start_of_compressed_data + self.compressed_size > cursor.get_ref().len() as u64 {
            return Err(Error::Parse("Invalid compressed data length"));
        }

        Ok(())
    }
```

If we define an enum for errors that implements `thiserror` traight, and define our own `Read`-error, we don't need the `Box<dyn`-stuff to handle multiple types of error structs.  Then we can also combine `parse` and `parse_internal`, and do away with `[.is::<...>](e.is::<ALZParseError>())`. 

There's probably an even better way to do this than the `.map_err(|_| Error::Read("uncompressed_size"))?` thing I suggest, but it works okay to convert the read error over to own own error type.  

I wasn't sure how to describe this, just suggesting all the code for the function. 

I'm also not sure about the error message I suggested for the `read_exact()`-error.

2024-03-15 14:08 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +    pub fn is_supported(&self) -> Result<(), ALZUnsupportedError> {
```suggestion
    pub fn is_supported(&self) -> Result<(), Error> {
```

Then return `Err(Error::UnsupportedFeature("... some explanation ... "))` for errors.

2024-03-15 14:09 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +    ) -> Result<(), ALZExtractError> {
```suggestion
    ) -> Result<(), Error> {
```

2024-03-15 14:09 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +    ) -> Result<(), ALZExtractError> {
Same deal here and later on with returning the error enum instead of specific type of error struct.

2024-03-15 14:10 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +        }
```suggestion
        if let Err(err) = local_fileheader.parse(cursor) {
            debug!("{err}");
            return false;
        }
```

Can use `if let` the same as you did with `.is_supported()`.

2024-03-15 14:17 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +                    )));
```suggestion
                    return Err(Error::UnrecognizedSig(format!("{:x}", sig)));
```

I love your use of `format!()` with `{:x}`. It was tempting to use the `Parse` enum variant, but that takes a `&str` cause those messages are all constants, so I added an extra enum variant for this one to keep your `format!()`.

2024-03-15 17:03 UTC, ragusaa commented
> Over all I'm super impressed with this being your first large amount of Rust code. Pretty awesome.

Thank you, I am starting to really like rust.

2024-03-15 17:26 UTC, ragusaa commented on clamscan/manager.c
> +
I think I agree.  I initially started copying one of the other archive formats, but I can't think of a reason anyone would want to open some types of archives and not others, if that is what they have.

2024-03-15 17:43 UTC, ragusaa commented on libclamav_rust/src/alz.rs
> +/* END ERRORS */
I like easy and cool features.

2024-03-22 19:30 UTC, micahsnyder requested changes
A few minor things this time.  My main concern is I don't think we should use `info!` at all.  We've gotten (understandable) complaints about the "early end" warnings in the PDF parser.  Users get confused by warnings when scanning malformed (but non-malicious) files. 

In the future, we would want to record such events as weak indicators that could be used by signatures.  That is of course pending implementing the weak indicator feature.   Anyways... I ramble. 

Final thing -- there is a linker error when building on Windows.  It seems that the bzip-sys crate is compiling bzip2-1.0.8 *into* our libclamav_rust static library.  That of course causes a linker error when we link libclamav (+libclamav_rust) with bz2.dll. 
I'm not sure how to solve it.  I created this issue to seek help: https://github.com/alexcrichton/bzip2-rs/issues/102

2024-03-22 19:30 UTC, micahsnyder commented on libclamav/scanners.c
>                  ret = scan_onenote(ctx);
Huh I didn't follow convention with `cli_scanonenote`. Ah well.

2024-03-22 19:30 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +            info!("Uncompressed file has different lengths for compressed vs uncompressed, using the shorter");
```suggestion
            debug!("Uncompressed file has different lengths for compressed vs uncompressed, using the shorter");
```

2024-03-22 19:30 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +            info!("Invalid data length");
```suggestion
            debug!("Invalid data length");
```

2024-03-22 19:30 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +            info!("Unable to decompress bz2 data");
```suggestion
            debug!("Unable to decompress bz2 data");
```

2024-03-22 19:30 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +            info!("{err}");
```suggestion
            debug!("{err}");
```

2024-03-22 19:30 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +use log::{debug, info};
```suggestion
use log::debug;
```

2024-03-22 19:30 UTC, micahsnyder commented on libclamav_rust/src/alz.rs
> +        }
```suggestion
    pub fn is_supported(&self) -> Result<(), Error> {
        if self.is_encrypted() {
            return Err(Error::UnsupportedFeature("Encryption Unsupported"));
        }

        if self.is_data_descriptor() {
            return Err(Error::UnsupportedFeature("Data Descriptors are Unsupported"));
        }
```

2024-03-25 21:02 UTC, ragusaa commented
> A few minor things this time. My main concern is I don't think we should use `info!` at all. We've gotten (understandable) complaints about the "early end" warnings in the PDF parser. Users get confused by warnings when scanning malformed (but non-malicious) files.
> 
> In the future, we would want to record such events as weak indicators that could be used by signatures. That is of course pending implementing the weak indicator feature. Anyways... I ramble.
> 
> Final thing -- there is a linker error when building on Windows. It seems that the bzip-sys crate is compiling bzip2-1.0.8 _into_ our libclamav_rust static library. That of course causes a linker error when we link libclamav (+libclamav_rust) with bz2.dll. I'm not sure how to solve it. I created this issue to seek help: [alexcrichton/bzip2-rs#102](https://github.com/alexcrichton/bzip2-rs/issues/102)

I agree on the info!.

So we'll wait to merge until we resolve the link issue?

2024-03-25 21:48 UTC, ragusaa commented
Re-ran testing with your changes, and everything still looks good.

2024-04-13 18:52 UTC, micahsnyder commented
I just rebased it, fixed merged conflicts, and squashed commits down, and re-ran clam-format once more.

2024-04-13 21:04 UTC, micahsnyder approved these changes
Jenkins test pipeline looks good to me as well.

2024-04-15 17:03 UTC, merged