Clam 2585 ole check encrypted 3
Cisco-Talos/clamav pull request #1295
Opened 2024-06-28 14:35 UTC by ragusaa

2024-06-28 17:46 UTC, micahsnyder commented
Replaced by https://github.com/Cisco-Talos/clamav/pull/1279

2024-06-28 19:51 UTC, micahsnyder commented
My mistake, this one replaces the other.

2024-07-17 22:26 UTC, micahsnyder requested changes
Other the formatting, I don't have any other concerns.

2024-07-17 22:26 UTC, micahsnyder commented on libclamav/ole2_extract.c
> +            if (encryption_status.encryption_type){
Minor formatting issues:
- extra new line 
- missing space between `){`

2024-07-17 22:26 UTC, micahsnyder commented on libclamav/ole2_extract.c
> +        const char * const OLE2_HEURISTIC_ENCRYPTED_WARNING = "Heuristics.Encrypted.OLE2";
Formatting got all funky here.

2024-07-18 17:14 UTC, ragusaa commented on libclamav/ole2_extract.c
> +        const char * const OLE2_HEURISTIC_ENCRYPTED_WARNING = "Heuristics.Encrypted.OLE2";
Ran clam-format.

2024-07-18 17:14 UTC, ragusaa commented on libclamav/ole2_extract.c
> +            if (encryption_status.encryption_type){
Ran clam-format.

2024-07-18 17:15 UTC, ragusaa commented
I ran clam-format to clean up the formatting, so I think this one is good to go.

2024-07-22 16:28 UTC, micahsnyder commented
Just rebased with upstream main to get the CI fixes and other clang-format fixes.

2024-07-22 17:17 UTC, micahsnyder approved these changes

2024-09-10 15:51 UTC, micahsnyder commented
Rebased again

2024-09-11 16:27 UTC, merged