Add regex support for OnAccessExcludePath
Cisco-Talos/clamav pull request #1314
Opened 2024-07-22 20:58 UTC by b1tg

Fix https://github.com/Cisco-Talos/clamav/issues/1074

To efficiently iterate over all watching files, I've introduced a linked list within `struct onas_ht` to keep track of all active buckets. Would this approach be effective for our purposes? @micahsnyder

2024-08-09 20:59 UTC, micahsnyder requested changes
It seems to work.

I did some basic tests with it using the following:
```
OnAccessIncludePath /home/micah/tmp
OnAccessExcludePath /home/micah/tmp/ignore.*
```

I started `clamonacc` and then touched a copy of `eicar` in each of `tmp` and `tmp/ignoreme` directories:
```
❯ touch ~/tmp/ignoreme/eicar
❯ touch ~/tmp/eicar
```

clamd logs:
```
❯ sudo /opt/sbin/clamonacc -F --ping 60 --wait --verbose
ClamClient: Connected.
ClamClient: client setup for continuous scanning
Clamonacc: daemon is local
ClamFanotif: kernel-level blocking feature disabled ...
ClamFanotif: max file size limited to 5242880 bytes
ClamScanQueue: initializing event queue consumer ... (5) threads in thread pool
Clamonacc: beginning event loops
ClamFanotif: starting fanotify event loop with process id (6931) ...
ClamInotif: starting inotify event loop ...
ClamInotif: dynamically determining directory hierarchy...
ClamScanQueue: waiting to consume events ...
ClamInotif: watching '/home/micah/tmp' (and all sub-directories)
ClamInotif: excluding '/home/micah/tmp/ignoreme' (and all sub-directories)
Excluding temp directory: /tmp
ClamInotif: NVM, didn't actually need to exclude '/tmp'
ClamMisc: $/proc/7072 vanished before UIDs could be excluded; scanning anyway
ClamFanotif: attempting to feed consumer queue
ClamWorker: performing scanning on file '/home/micah/tmp/eicar'
ClamFanotif: /home/micah/tmp/eicar skipped (excluded UID)
ClamFanotif: /home/micah/tmp/eicar skipped (excluded UID)
/home/micah/tmp/eicar: Win.Test.EICAR_HDB-1 FOUND
```

So I cans ee it correctly excluded `ignoreme` and then with my touch commands it only scans the `tmp/eicar` file. 👍 

Can I trouble you to add some inline documentation to explain the purpose for each thing?

2024-08-09 20:59 UTC, micahsnyder commented on clamonacc/inotif/inotif.c
> +            struct onas_bucket *ob = ddd_ht->head;
Inline comments for these new `while` loops would also be appreciated.

2024-08-09 20:59 UTC, micahsnyder commented on clamonacc/inotif/hash.c
> +    if (ht->nbckts == 0) {
Some inline comments to explain this would be handy.

2024-08-12 19:10 UTC, micahsnyder reviewed
Thanks. Not a lot of detail 😆  but good enough.

Thanks. Will approve and merge after the clamav 1.4.0 release.

2024-09-26 16:31 UTC, micahsnyder approved these changes

2024-09-26 16:33 UTC, micahsnyder commented
Rebased and squashed

2024-10-02 15:25 UTC, b1tg commented
"continuous-integration/jenkins/pr-head" failed and I can't access the details URL, any thing need my fix? @micahsnyder

2024-10-02 16:01 UTC, micahsnyder commented
@b1tg it always fails, because of a handful of tests that need work. In this case, it actually failed to get past our initial gitguardian stage (expired token). I forgot to check in on this though. I'm re-running it now. 🤞

2024-10-04 16:33 UTC, b1tg commented
Failed again😭

2024-10-09 20:48 UTC, micahsnyder commented
The signing issue turned out to be xcode wanting me to approve signing in the GUI. The internal tests looked good, though the Jenkins stage will show an ❌ because we have some expected test failures.

2024-10-09 20:49 UTC, merged