cdiff: Inital rust port of the cdiff library: cdiff-apply
Cisco-Talos/clamav pull request #387
Opened 2021-11-24 00:18 UTC by micahsnyder

This is a rebased version of https://github.com/Cisco-Talos/clamav/pull/302 with merge conflicts fixed and with the `eprintln!()` macros replaced with `debug!()`, `error!()`, etc now that the `libclamav_rust::logging` module is merged into `main`.

99% of the work done by @jhumlick, not me. Thanks John!

2021-11-24 00:32 UTC, jhumlick requested changes
debug! should not be used in cases where a fatal error occurs.

2021-11-24 00:32 UTC, jhumlick commented on libclamav_rust/src/cdiff.rs
> +                debug!("{:?}", e.to_string());
Fatal errors should not be shown only at the debug log level.

2021-11-24 00:32 UTC, jhumlick commented on libclamav_rust/src/cdiff.rs
> +            debug!("cdiff_apply: Incorrect digital signature");
Fatal errors should not be shown only at the debug log level.

2021-11-24 00:32 UTC, jhumlick commented on libclamav_rust/src/cdiff.rs
> +                debug!("{}", e.to_string());
Fatal errors should not be shown only at the debug log level.

2021-11-24 00:32 UTC, jhumlick commented on libclamav_rust/src/cdiff.rs
> +            debug!("{}", e.to_string());
Fatal errors should not be shown only at the debug log level.

2021-11-24 01:10 UTC, jhumlick approved these changes

2021-11-29 16:53 UTC, jhumlick approved these changes

2021-12-03 21:43 UTC, jhumlick approved these changes

2021-12-07 00:33 UTC, micahsnyder commented
Looks like we also have a Windows build failure and a CIFuzz build failure.  I'll try to figure out what's going on with those when I'm able to look at it some more.

2022-01-07 23:43 UTC, micahsnyder commented
Replaced by https://github.com/Cisco-Talos/clamav/pull/400

2022-01-07 23:43 UTC, closed without merging