Clam 1651 memory leaks
Cisco-Talos/clamav pull request #532
Opened 2022-04-06 17:02 UTC by ragusaa

This addresses the pdb memory leaks in the ticket.  Will do separate PRs for other issues that are not in the same files.

2022-04-19 20:50 UTC, micahsnyder requested changes
Looks like this was changed (slightly differently) in https://github.com/Cisco-Talos/clamav/pull/530/files#diff-c2d7ebcb1295f163964c14d878838c83e69061189c318f01909d34dd5a383a98L427-L466

This version:
- isn't clang-formatted 
- doesn't use the VERIFY_POINTER macros
- does have better error handling for the `parse_regex()` call.  

How do you want to proceed?  Do you want to merge these two PR's?  Do you want to take the improvements from this one and put them in #530?  Or?

2022-04-26 17:34 UTC, micahsnyder commented
From offline conversation: because of the overlap with #530, the plan is to fix-up that one and merge that first -- then rebase this and fix the merge conflicts, and then merge this.  So until #530 lands, this one is blocked.

2022-05-17 18:25 UTC, ragusaa commented
The updates to PR-530 appear to have removed the merge conflicts, because when I did a 'git pull', there was nothing to merge.  I clang-formatted, so I am ready for re-review.

2022-05-27 23:49 UTC, micahsnyder commented
Everything checks out.  This was a little difficult to verify because the 2 PoC's for this were mixed in with 4 PoC's for related issues.  But manual testing confirmed all is well with this PR.

2022-05-27 23:50 UTC, micahsnyder approved these changes

2022-05-27 23:51 UTC, merged