Clam 1619 cmake rust improvements
Cisco-Talos/clamav pull request #694
Opened 2022-09-07 20:57 UTC by micahsnyder

This PR solves two issues:
1. precompiling the rust unit test executable so it is not compiled during test run time.
2. building all rust modules in same target directory, so we don't recompile any dependencies.

This significantly reduces test time in this project, and the equivalent changes in my CMake-Rust Demo project found a more significant improvement in build time because it has more than one Rust target, with some common dependencies: https://github.com/micahsnyder/cmake-rust-demo/pull/9

2022-09-07 21:33 UTC, shutton requested changes
Minor stuff

2022-09-13 20:09 UTC, micahsnyder commented on libclamav_rust/build.rs
> +        .write_to_file(BINDGEN_OUTPUT_FILE)
No bonus points for me today. I just need to merge this and move on to more pressing tasks.

2022-09-13 22:00 UTC, micahsnyder commented
This build is failing on windows because the logic I use to provide the environment variables for the libclamav_rust executable (see 'libclamav_rust_test' CMake target) is including the PATH, and the path has more than one item on Windows that is *space* separated... That doesn't work.  It makes the `.bat` script into some nonsense that fails with "Access denied". 

I'll work on a solution.

2022-09-16 19:32 UTC, shutton approved these changes

2022-09-16 20:05 UTC, merged