Add an option to avoid setting RPATH on unix systems.
Cisco-Talos/clamav pull request #815
Opened 2023-01-22 19:55 UTC by sebastianas

RPATH overrides the normal library search path, possibly interfering with local policy and causing problems for multilib, among other issues.

Add an option to avoid setting it with letting it enabled by default.

Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>

2023-01-26 23:26 UTC, micahsnyder commented
Thanks for submitting this Sebastian.  

Casually reading this, it makes sense to me.  As noted on the other PR, this week has been hectic and I expect that week will be as well. I will give it more attention as soon as I can.

2023-03-09 21:09 UTC, micahsnyder commented
Can you please also document the new option in https://github.com/Cisco-Talos/clamav/blob/main/INSTALL.md#custom-cmake-config-options

Outside of this documentation request, I'm happy with the PR.

2023-03-09 21:10 UTC, micahsnyder requested changes
Forgot to mark "request changes" for documentation change. Required to add a comment in order to do it ;-)

2023-03-10 22:24 UTC, sebastianas commented
done

2023-03-19 04:04 UTC, micahsnyder requested changes
Some other very minor changes to make, please.

2023-03-19 04:04 UTC, micahsnyder commented on INSTALL.md
> +
This is missing this line that the rest of the options have
```md
  _Default: `OFF`_
```

2023-03-19 04:04 UTC, micahsnyder commented on CMakeOptions.cmake
> +	"Don't set the RPATH on UNIX systems.")
Indentation here is a little off, using a tab instead of 4 spaces.

2023-03-23 16:50 UTC, micahsnyder approved these changes
Because my requested changes here were miniscule, I did it myself and will just squash the extra fixup commits in the merge.

2023-03-23 16:51 UTC, merged