Clam 571 sigtool vba extraction improvements
Cisco-Talos/clamav pull request #852
Opened 2023-03-06 14:20 UTC by ragusaa

This PR deduplicates some vba extraction logic so sigtool works the same way libclamav does, and so it can extract more things.

2023-03-21 02:18 UTC, micahsnyder commented
In testing I tried using the ` --vba-hex=FILE ` option and it failed:
```

❯ ./install/bin/sigtool --vba-hex=$HOME/Downloads/1b96c0ad7ce83a573ec7770435655fa2c82c42ea43bd012dd0b64444941c9432
scanfile: Invalid args.
```

2023-03-22 22:13 UTC, micahsnyder requested changes

2023-03-22 22:13 UTC, micahsnyder commented on sigtool/sigtool.c
> +static bool setTempDir(struct cl_engine *engine, const struct optstruct *opts)
I wonder if there are other features in sigtool that could make use of setting the temp directory like this, and also the option to leaving temp files.

2023-03-22 22:13 UTC, micahsnyder commented on sigtool/sigtool.c
> +    options.parse |= CL_SCAN_PARSE_XMLDOCS;
Do we also need `CL_SCAN_PARSE_OLE2`?

2023-03-22 22:13 UTC, micahsnyder commented on sigtool/sigtool.c
> +    }
cl_scandesc_callback is already a recursive process, so I would think that the process of adding files from the json to scan later would not be required.  Maybe we can message offline about it so I can understand this better

2023-03-23 17:17 UTC, ragusaa commented on sigtool/sigtool.c
> +    if (!optget(opts, "leave-temps")->enabled) {
I like that idea.  I am find changing it, but the behavior will be different than clamscan.

2023-03-23 19:15 UTC, ragusaa commented on libclamav/vba_extract.c
change callback to normalized data.

2023-03-23 19:25 UTC, micahsnyder requested changes

2023-03-23 19:25 UTC, micahsnyder commented on libclamav/clamav.h
> +extern void cl_engine_set_clcb_vba(struct cl_engine *engine, clcb_vba callback);
```suggestion
extern void cl_engine_set_clcb_vba(struct cl_engine *engine, clcb_generic_data callback);
```

2023-03-23 19:25 UTC, micahsnyder commented on libclamav/others.h
> +    clcb_vba cb_vba;
```suggestion
    clcb_generic_data cb_vba;
```

2023-03-30 05:21 UTC, merged